### ISSUE TITLE
SFX module licenses

### ISSUE THREAD

**Issue by bgermann** [ssokolow/rar-test-files#1]
In README.md you claim "While I don't hold copyright to the self-extractor stubs present in the .exe and .bin self-extracting test archives, they may be redistributed freely."

Unfortunately, there are 3rd party licenses that apply to the SFX modules. You can find them in the acknow.txt file that is in the RAR distributions. For the RAR versions that I have had a look at, it holds two BSD licenses that apply. I have verified that with Eugene Roshal.

**Comment by bgermann** [comment]
WinRAR has an option to include license texts in SFX modules. Maybe you want to make use of that for including them. Or just copy the acknow.txt to the project directory.

**Comment by ssokolow** [comment]
Well, that's inconsiderate of him. Even knowing to look for that, there's no `acknow.txt` in `wrar601b1.exe` and the mention of the "Acknowledgments" help file topic in `License.txt` makes it sound like it's only relevant to the WinRAR portion you're *not* allowed to redistribute while properly licensed.

Definitely a reason I'd never use or promote WinRAR for creating *new* archives other than as test files. It makes just staying legally compliant when redistributing an archive into a footgun.

I have to go out for an appointment, but I'll figure out how to read the Acknowledgements section (Wine's Windows Help viewer doesn't like the WinRAR help file, so I need another tool) after I get back.

That said, none of the files in `rarx393.exe` (the DOS version) make mention of that and there's no such option listed in its manual, RAR for DOS's `/?` output, or any mention of additiona license terms in the self-extractor's `/?` output, so I think I'm compliant there.

As for the Linux version, it got flushed out as part of reinstalling my system, so I'll take the opportunity to switch to a pinned version like with the DOS and Windows versions after I get back and get `acknow.txt` then.

Thanks for bringing this to my attention. I think WinRAR is the only program I've ever encountered where the generated self-extracting archives have license compliance requirements above and beyond "just send what was generated to the intended recipient".

(There *is* an ambiguous bit in the StuffIt for Windows license about needing a license to redistribute their self-extractor stub for Zip files, but it probably just means "you can't share Zip self-extractors generated by an evaluation copy of StuffIt." InfoZIP's stub actually has a special clause in the license which allows you to accept the very short attribution message in the output of the default build of the SFX stub instead of having to carry along the whole license text.)

Heck, for the DOS equivalent to Inno Setup or NSIS that I'm intermittently working on as a hobby project, I tracked down some public domain unzipping code and I'm putting everything I write under the zlib/libpng license so binary builds don't have to either be distributed with a print copy of a license or bloat out the floppy disk image with a digital copy.

**Comment by bgermann** [comment]
I do not know about such old versions. I just checked the Debian archive and it seems [acknow.txt](https://sources.debian.org/src/rar/2:5.5.0-1/acknow.txt/) was introduced with version 4.

**Comment by ssokolow** [comment]
Yeah. That's the last DOS version and, even without an SFX stub, RAR files indicate whether they come from DOS or Win32 well enough for `file` to say, so it was important to cover that axis of variation.

I'll make sure that the acknowledgements are the same for the Windows and Linux versions when I get back, and then rebuild the self-extractors with `acknow.txt` inside them for maximum ease of use.

(You said there's an option to include license texts in SFX modules. Do you know what the command-line version is? ...because I'm not seeing anything that looks like that when I scan through the output of `Rar.exe /?` from `wrar601b1.exe`.)

**Comment by ssokolow** [comment]
In fact, the only option I can find that's even remotely like that in the WinRAR GUI is the standard "for displaying things like EULAs for the *contained* files" License dialog option that requires you to provide the text manually.

That said, looking at `acknow.txt`, my suspicion is that it was added when RAR gained support for AES encryption. That's one of only two things in there that are actual required licenses rather than what look like "courtesy acknowledgements" and I suspect "I don't trust myself to reimplement AES from scratch securely" is what prompted the switch to using things which require attribution like that.

**Comment by ssokolow** [comment]
I just noticed the e-mail you forwarded via my contact form and that raises another possibility. Was the option to add the license text to SFX archives added after `wrar601b1.exe`?

**Comment by bgermann** [comment]
I checked it on the GUI of the latest WinRAR version, so that might be possible.

**Comment by ssokolow** [comment]
I've gotta go now, but I'll try a newer WinRAR version after I get back and see what effect that has on the reproducible builds I've got set up.

If it doesn't cause a mass change to all the non-SFX archives, and it allows me to just embed the acknowledgements with a simple command-line switch, I'll update to it. Otherwise, I'll manually add the file.

**Comment by ssokolow** [comment]
I just upgraded my copy of WinRAR to a freshly downloaded 6.02 and I still can't find any kind of "automatically include acknowledgements for SFX stub in the archive" setting in either the WinRAR GUI or the Rar.exe command-line tool.

Could you point me at the one you're seeing in yours?

(I'd really prefer not to have to manually make sure the copy of `acknow.txt` stays in sync with the tooling if there's an alternative that'll bundle the proper version automatically.)

I also downloaded RAR 6.02 for Linux and, while I now have a copy of `acknow.txt` that I've confirmed to contain the same relevant information as `WinRAR.chm` except in a single-page format, that doesn't appear to have an equivalent option to automatically bundle the right version of it into a Linux self-extractor either.

**Comment by bgermann** [comment]
There is no option to include acknow.txt automatically. There is a generic license option and I think it is a GUI-only thing.

**Comment by ssokolow** [comment]
There you go.

I looked through the older versions and I don't see anything like `acknow.txt` for the DOS version of 3.9.3, but the Windows version of 3.9.3 *does* include that license declaration for Brian Gladman's AES implementation, so I guess I have to include `acknow.txt` in the DOS SFX test file too.

I added a thank you note for you to the README because I put so much effort into getting this license-compliant and I would have never noticed that.

**Comment by bgermann** [comment]
Thanks. Your test files were appreciated in the porting of [unrar-free](https://gitlab.com/bgermann/unrar-free) to libarchive.

**Comment by ssokolow** [comment]
:)

Let me know if there are any other configurations you need test files for. The only reason I stopped where I did is that I'm not yet certain about all the combinations that need to be covered.

**Comment by bgermann** [comment]
FYI: According to WinRAR 6.10 Beta 1's acknow.txt, the SFX modules are now freed of the BSD licenses.

**Comment by ssokolow** [comment]
Thanks.

Barring a more pressing reason, I'll decide whether to redo things when I get around to working on one of the other TODO list entries.
